FROM ubuntu:24.04

RUN apt-get update -o Acquire::ForceIPv4=true \
    && apt-get install -y \
        curl \
        ca-certificates \
        zstd \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL \
    https://github.com/ollama/ollama/releases/latest/download/ollama-linux-amd64.tar.zst \
    | zstd -d | tar -xf - -C /

EXPOSE 11434
ENV OLLAMA_HOST=0.0.0.0

ENTRYPOINT ["ollama"]
CMD ["serve"]
